PIWEB/src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PanierRepository::class)]
class Panier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $prod_name = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?int $panier_id = null;

    #[ORM\ManyToOne(inversedBy: 'Panier')]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProdName(): ?string
    {
        return $this->prod_name;
    }

    public function setProdName(string $prod_name): static
    {
        $this->prod_name = $prod_name;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getPanierId(): ?int
    {
        return $this->panier_id;
    }

    public function setPanierId(int $panier_id): static
    {
        $this->panier_id = $panier_id;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

PIWEB/src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\PanierRepository;

class PanierType extends AbstractType
{
    private $entityManager;
    private $panierRepository;

    public function __construct(EntityManagerInterface $entityManager, PanierRepository $panierRepository)
    {
        $this->entityManager = $entityManager;
        $this->panierRepository = $panierRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        // Récupérez la valeur maximale de panier_id
        $maxPanierId = $this->panierRepository->getMaxPanierId();

        // Ajoutez 1 à la valeur maximale pour obtenir la nouvelle valeur de panier_id
        $newPanierId = $maxPanierId + 1;

        $builder
            ->add('prod_name', TextType::class, [
                'label' => 'Nom du produit',
                'data' => $options['nom_produit'],
                'attr' => ['readonly' => true]
            ])
            ->add('quantity', NumberType::class, [
                'label' => 'Quantite',
                'data' => $options['quantity'],
                'attr' => ['readonly' => true]
            ])
            ->add('price', NumberType::class, [
                'label' => 'Price',
                'data' => $options['prix_produit'],
                'attr' => ['readonly' => true], 
            ])
            ->add('date', DateType::class, [
                'label' => 'Date',
                'data' => new \DateTime(), 
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => ['readonly' => true]
            ])
            ->add('panier_id', NumberType::class, [
                'label' => 'ID du panier',
                'data' => $newPanierId,
                'attr' => ['readonly' => true]
            ])
            ->add('User', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
                'label' => 'User',
                'data' => $this->entityManager->getReference(User::class, 1), // Récupère l'utilisateur avec l'ID 1 depuis la base de données
                'attr' => ['readonly' => true],
            ]);

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($options) {
            $form = $event->getForm();
            $data = $event->getData();
          
            if ($data instanceof Panier && null !== $data->getQuantity() && isset($options['prix_produit'])) {
                $quantity = $data->getQuantity();
                $initialPrice = $options['prix_produit'];
                $newPrice = $quantity * $initialPrice;

                // Set the new price value to the price field
                $form->get('price')->setData(12);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
            'nom_produit' => null,
            'prix_produit' => null,
            'quantity' => null, // Définir l'option "quantity" avec une valeur par défaut
        ]);
    }
}

PIWEB/src/Controller/PanierController.php
<?php

namespace App\Controller;
use App\Entity\Panier;
use App\Entity\Produits;
use App\Form\PanierType;
use App\Form\Panier1Type;
use App\Repository\PanierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/panier')]
class PanierController extends AbstractController
{
    #[Route('/', name: 'app_panier_index', methods: ['GET'])]
    public function index(PanierRepository $panierRepository): Response
    {   $maxPanierId = $panierRepository->getMaxPanierId();

        return $this->render('panier/index.html.twig', [
            'paniers' => $panierRepository->findAll(),
            'max_panier_id' => $maxPanierId,
        ]);
       
       
    }
  
  
    #[Route('/back', name: 'app_panier_indexback', methods: ['GET'])]
    public function indexback(PanierRepository $panierRepository): Response
    {
        return $this->render('panier/indexback.html.twig', [
            'paniers' => $panierRepository->findAll(),
        ]);
    }

#[Route('/new1', name: 'app_panier_new1', methods: ['GET', 'POST'])]
public function new1(Request $request, EntityManagerInterface $entityManager): Response
{
    // Récupérer le nom du produit et le prix du produit à partir de la requête
    $nomProduit = $request->query->get('nomProduit');
    $prixProduit = $request->query->get('prixProduit');
    $quantity = $request->request->get('quantity');
    $stockProduit = $request->query->get('stock');
   // $prixProduit = intval($request->query->get('prixProduit'));
   $produitRepository = $entityManager->getRepository(Produits::class);
   $produit = $produitRepository->findProduitByNom($nomProduit);
   $produit->setStock($produit->getStock() - $quantity);

   // Enregistrer les modifications du produit dans la base de données
   $entityManager->persist($produit);
   $entityManager->flush();
    // Créer une instance de Panier
    $panier = new Panier();

    // Créer le formulaire et passer le nom et le prix du produit en option
    $form = $this->createForm(Panier1Type::class, $panier, [
        'nom_produit' => $nomProduit,
        'prix_produit' => $prixProduit*$quantity,
        'quantity' => $quantity,

    ]);

    // Gérer la soumission du formulaire
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // Traiter les données du formulaire

        // Enregistrer le panier en base de données
        $entityManager->persist($panier);
        $entityManager->flush();

        // Rediriger l'utilisateur vers la page de l'index du panier
        return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
    }

    // Afficher le formulaire dans le template Twig
    return $this->renderForm('panier/new.html.twig', [
        'panier' => $panier,
        'form' => $form,
    ]);
}

    #[Route('/new', name: 'app_panier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        // Récupérer le nom du produit et le prix du produit à partir de la requête
        $nomProduit = $request->query->get('nomProduit');
        $prixProduit = $request->query->get('prixProduit');
        $quantity = $request->request->get('quantity');
        $stockProduit = $request->query->get('stock');
       // $prixProduit = intval($request->query->get('prixProduit'));
       $produitRepository = $entityManager->getRepository(Produits::class);
       $produit = $produitRepository->findProduitByNom($nomProduit);
       $produit->setStock($produit->getStock() - $quantity);

       // Enregistrer les modifications du produit dans la base de données
       $entityManager->persist($produit);
       $entityManager->flush();
        // Créer une instance de Panier
        $panier = new Panier();

        // Créer le formulaire et passer le nom et le prix du produit en option
        $form = $this->createForm(PanierType::class, $panier, [
            'nom_produit' => $nomProduit,
            'prix_produit' => $prixProduit*$quantity,
            'quantity' => $quantity,

        ]);

        // Gérer la soumission du formulaire
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Traiter les données du formulaire

            // Enregistrer le panier en base de données
            $entityManager->persist($panier);
            $entityManager->flush();

            // Rediriger l'utilisateur vers la page de l'index du panier
            return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        // Afficher le formulaire dans le template Twig
        return $this->renderForm('panier/new.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_panier_show', methods: ['GET'])]
    public function show(Panier $panier): Response
    {
        return $this->render('panier/show.html.twig', [
            'panier' => $panier,
        ]);
    }
    #[Route('/{id}/showback', name: 'app_panier_showback', methods: ['GET'])]
    public function showback(Panier $panier): Response
    {
        return $this->render('panier/showback.html.twig', [
            'panier' => $panier,
        ]);
    }
    #[Route('/{id}/edit', name: 'app_panier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Panier $panier, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_panier_indexback', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('panier/edit.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_panier_delete', methods: ['POST'])]
    public function delete(Request $request, Panier $panier, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$panier->getId(), $request->request->get('_token'))) {
            $entityManager->remove($panier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
    }
 
    
    #[Route('/panier/{panierId}/produits', name: 'app_panier_produits')]
    public function afficherProduitsDuPanier(int $panierId, PanierRepository $panierRepository): Response
    {
        $produits = $panierRepository->findProdDetailsByPanierId($panierId);
        $totalPrice = 0;

        // Calculer le total des prix
        foreach ($produits as $produit) {
            $totalPrice += $produit['price'];
        }
    
        return $this->render('panier/total.html.twig', [
            'produits' => $produits,
            'totalPrice' => $totalPrice,

        ]);
    }
    #[Route('/panier/{panierId}/Paiement', name: 'app_paiement')]
    public function Payer(int $panierId, PanierRepository $panierRepository): Response
    {
        $produits = $panierRepository->findProdDetailsByPanierId($panierId);
        $totalPrice = 0;

        // Calculer le total des prix
        foreach ($produits as $produit) {
            $totalPrice += $produit['price'];
        }
    
        return $this->render('panier/Payer.html.twig', [
            'produits' => $produits,
            'totalPrice' => $totalPrice,

        ]);
    }

   
    
     /**
     * @Route("/paiement", name="paiement")
     */
    public function paiement(): Response
    {
        // Vous pouvez ajouter du code ici si nécessaire pour la page de paiement
        // Par exemple, récupérer les informations du panier, afficher un récapitulatif, etc.
        return $this->render('stripe/index.html.twig');
    }
    
    
}



    
   

PIWEB/templates/panier/Payer.html.twig
{% extends 'front.html.twig' %}

    {% block body %}
        <div class="container">
            <h1>Paiement des Produits</h1>
    
            <!-- Afficher les produits à payer -->
            <table class="table">
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Quantité</th>
                        <th>Prix</th>
                    </tr>
                </thead>
                <tbody>
                    {% for produit in produits %}
                        <tr>
                            <td>{{ produit.prod_name }}</td>
                            <td>{{ produit.quantity }}</td>
                            <td>{{ produit.price }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
    
            <!-- Afficher le total des prix -->
            <div>
                <p>Total à payer : {{ totalPrice }} €</p>
            </div>
    
            <!-- Formulaire de paiement Stripe -->
            <form id="payment-form">
                <div class="form-group">
                    <label for="card-element">Carte de crédit ou de débit</label>
                    <div id="card-element"></div>
                    <div id="card-errors" role="alert"></div>
                </div>
    
                <button id="submit-button" class="btn btn-primary">Payer {{ totalPrice }} €</button>
            </form>
        </div>
    
        <!-- Inclure le script de l'API Stripe -->
        <script src="https://js.stripe.com/v3/"></script>
    
        <!-- Votre script JavaScript pour gérer le paiement -->
        <script>
            var stripe = Stripe("{{'pk_test_51OphDrASsnDruPyJX2OalNMOju1tFjPnPhY4QvHVOswrsC309XLyZdNEwAxzCveIEXGvezcvzSyui2bFHqkWvY0X001M4Vqd1Y'}}");
            var elements = stripe.elements();
            var cardElement = elements.create('card');
            cardElement.mount('#card-element');
    
            var form = document.getElementById('payment-form');
            var submitButton = document.getElementById('submit-button');
    
            form.addEventListener('submit', function(event) {
                event.preventDefault();
                stripe.createPaymentMethod({
                    type: 'card',
                    card: cardElement,
                }).then(function(result) {
                    if (result.error) {
                        var errorElement = document.getElementById('card-errors');
                        errorElement.textContent = result.error.message;
                    } else {
                        stripeTokenHandler(result.paymentMethod);
                    }
                });
            });
    
            function stripeTokenHandler(paymentMethod) {
                // Ajoutez ici la logique pour envoyer le token au serveur et finaliser le paiement
                console.log(paymentMethod);
                alert('Paiement réussi !');
            }
        </script>
    {% endblock %}
    

PIWEB/templates/panier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="custom-button">{{ button_label|default('Acheter') }}</button>
{{ form_end(form) }}

PIWEB/templates/panier/index.html.twig
{% extends 'front.html.twig' %}

{% block title %}Panier index{% endblock %}

{% block body %}
    <h1>Panier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prod_name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Date</th>
                <th>Panier_id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for panier in paniers %}
            <tr>
                <td>{{ panier.id }}</td>
                <td>{{ panier.prodName }}</td>
                <td>{{ panier.quantity }}</td>
                <td>{{ panier.price }}</td>
                <td>{{ panier.date ? panier.date|date('Y-m-d') : '' }}</td>
                <td>{{ panier.panierId }}</td>
                <td>
                    <a href="{{ path('app_panier_show', {'id': panier.id}) }}">Show</a>
                    <a href="{{ path('app_panier_produits', {'panierId': panier.panierId}) }}" class="btn btn-success">Afficher total</a>

                    {% if panier.panierId == max_panier_id %}
                        <a href="{{ path('app_paiement', {'panierId': panier.panierId})}}" class="btn btn-danger">Payer</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Bouton "Retour vers le catalogue" -->
    <div>
        <a href="{{ path('app_produits_index1') }}" class="btn btn-primary">Retour vers le catalogue</a>
    </div>
{% endblock %}

PIWEB/templates/panier/index1.html.twig
{% extends 'front.html.twig' %}

{% block title %}Panier index{% endblock %}

{% block body %}
    <h1>Panier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prod_name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Date</th>
                <th>Panier_id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for panier in paniers %}
            <tr>
                <td>{{ panier.id }}</td>
                <td>{{ panier.prodName }}</td>
                <td>{{ panier.quantity }}</td>
                <td>{{ panier.price }}</td>
                <td>{{ panier.date ? panier.date|date('Y-m-d') : '' }}</td>
                <td>{{ panier.panierId }}</td>
                <td>
                    <a href="{{ path('app_panier_show', {'id': panier.id}) }}">Show</a>
                    <a href="{{ path('app_panier_produits', {'panierId': panier.panierId}) }}" class="btn btn-success">Afficher total</a>
                    </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Bouton "Retour vers le catalogue" -->
    <div>
        <a href="{{ path('app_produits_index1') }}" class="btn btn-primary">Retour vers le catalogue</a>
    </div>
{% endblock %}

PIWEB/templates/panier/indexback.html.twig
{% extends 'back.html.twig' %}

{% block title %}Panier index{% endblock %}

{% block body %}
    <h1>Panier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prod_name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Date</th>
                <th>Panier_id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for panier in paniers %}
            <tr>
                <td>{{ panier.id }}</td>
                <td>{{ panier.prodName }}</td>
                <td>{{ panier.quantity }}</td>
                <td>{{ panier.price }}</td>
                <td>{{ panier.date ? panier.date|date('Y-m-d') : '' }}</td>
                <td>{{ panier.panierId }}</td>
                <td>
                    <a href="{{ path('app_panier_showback', {'id': panier.id}) }}">Show</a>
                
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Bouton "Retour vers le catalogue" -->
    <div>
        <a href="{{ path('app_produits_indexback') }}" class="btn btn-primary">Retour vers le catalogue</a>
    </div>
{% endblock %}

PIWEB/templates/panier/show.html.twig
{% extends 'front.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
    <h1>Panier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ panier.id }}</td>
            </tr>
            <tr>
                <th>Prod_name</th>
                <td>{{ panier.prodName }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ panier.quantity }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ panier.price }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ panier.date ? panier.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Panier_id</th>
                <td>{{ panier.panierId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_panier_index') }}">back to list</a>

    <a href="{{ path('app_panier_edit', {'id': panier.id}) }}">edit</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}

PIWEB/templates/panier/showback.html.twig
{% extends 'Back.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
    <h1>Panier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ panier.id }}</td>
            </tr>
            <tr>
                <th>Prod_name</th>
                <td>{{ panier.prodName }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ panier.quantity }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ panier.price }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ panier.date ? panier.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Panier_id</th>
                <td>{{ panier.panierId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_panier_indexback') }}">back to list</a>

{% endblock %}

PIWEB/templates/panier/total.html.twig
{% extends 'front.html.twig' %}

{% block title %}Produits du panier{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .total-price {
            color: #001233; /* Votre couleur personnalisée ici */
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="mb-4">Produits du panier</h1>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Produit</th>
                    <th scope="col">Quantité</th>
                    <th scope="col">Prix</th>
                </tr>
            </thead>
            <tbody>
                {% for produit in produits %}
                    <tr>
                        <td>{{ produit.prod_name }}</td>
                        <td>{{ produit.quantity }}</td>
                        <td>{{ produit.price }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="mt-4">
            <p class="font-weight-bold">Total des prix :</p>
            <h2 class="total-price">{{ totalPrice }} €</h2>
        </div>

        <a href="{{ path('app_panier_index') }}" class="btn btn-primary mt-4">Retour au panier</a>
    </div>
{% endblock %}