src/Entity/Debat.php
<?php

namespace App\Entity;

use App\Repository\DebatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DebatRepository::class)]
class Debat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:5)]
    #[Assert\Length(max:20)]
    #[Assert\NotBlank (message:"veuillez saisir le sujet debat de debat")]
    private ?string $sujet_debat = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:5)]
    #[Assert\Length(max:20)]
    #[Assert\NotBlank (message:"veuillez saisir le description de debat")]
    private ?string $description_debat = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:5)]
    #[Assert\Length(max:20)]
    #[Assert\NotBlank (message:"veuillez saisir le nom anime de debat")]
    private ?string $nom_anime = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Length(min:1)]
    #[Assert\Length(max:5)]
    #[Assert\NotBlank (message:"veuillez saisir le description de debat")]
    private ?int $note_anime = null;

    #[ORM\ManyToOne(inversedBy: 'debats')]
    private ?Utilisateurs $User = null;

    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'Debat')]
    private Collection $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    #[ORM\Column(name: "noteanimes", nullable: true)]
    private ?int $noteanimes= null;
    
    public function getNoteanimes(): ?int
    {
        return $this->noteanimes;
    }
    
    public function setNoteanimes(?int $noteanimes): self
    {
        $this->noteanimes= $noteanimes;
        return $this;
    }
    public function __toString()
    {
        return $this->sujet_debat;
    }

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSujetDebat(): ?string
    {
        return $this->sujet_debat;
    }

    public function setSujetDebat(string $sujet_debat): static
    {
        $this->sujet_debat = $sujet_debat;

        return $this;
    }

    public function getDescriptionDebat(): ?string
    {
        return $this->description_debat;
    }

    public function setDescriptionDebat(string $description_debat): static
    {
        $this->description_debat = $description_debat;

        return $this;
    }

    public function getNomAnime(): ?string
    {
        return $this->nom_anime;
    }

    public function setNomAnime(string $nom_anime): static
    {
        $this->nom_anime = $nom_anime;

        return $this;
    }

    public function getNoteAnime(): ?int
    {
        return $this->note_anime;
    }

    public function setNoteAnime(?int $note_anime): static
    {
        $this->note_anime = $note_anime;

        return $this;
    }

    public function getUser(): ?Utilisateurs
    {
        return $this->User;
    }

    public function setUser(?Utilisateurs $User): static
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setDebat($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getDebat() === $this) {
                $commentaire->setDebat(null);
            }
        }

        return $this;
    }

    
    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToMany(targetEntity: Panier::class, mappedBy: 'user_id')]
    private Collection $prod_name;

    #[ORM\OneToMany(targetEntity: Panier::class, mappedBy: 'user_id')]
    private Collection $panier;

    #[ORM\OneToMany(targetEntity: Livraison::class, mappedBy: 'id_user')]
    private Collection $livraison;

    #[ORM\OneToMany(targetEntity: Cosplay::class, mappedBy: 'userid')]
    private Collection $cosplay;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $roles = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column]
    private ?int $cin = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?int $age = null;

    #[ORM\Column]
    private ?int $num_tel = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $is_verified = null;

    #[ORM\OneToMany(targetEntity: Debat::class, mappedBy: 'user_id')]
    private Collection $debat;

    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'User')]
    private Collection $Reservation;


    public function __construct()
    {
        $this->prod_name = new ArrayCollection();
        $this->panier = new ArrayCollection();
        $this->livraison = new ArrayCollection();
        $this->cosplay = new ArrayCollection();
        $this->debat = new ArrayCollection();
        $this->Reservation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getProdName(): Collection
    {
        return $this->prod_name;
    }

    public function addProdName(Panier $prodName): static
    {
        if (!$this->prod_name->contains($prodName)) {
            $this->prod_name->add($prodName);
            $prodName->setUserId($this);
        }

        return $this;
    }

    public function removeProdName(Panier $prodName): static
    {
        if ($this->prod_name->removeElement($prodName)) {
            // set the owning side to null (unless already changed)
            if ($prodName->getUserId() === $this) {
                $prodName->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPanier(): Collection
    {
        return $this->panier;
    }

    public function addPanier(Panier $panier): static
    {
        if (!$this->panier->contains($panier)) {
            $this->panier->add($panier);
            $panier->setUserId($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): static
    {
        if ($this->panier->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getUserId() === $this) {
                $panier->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Livraison>
     */
    public function getLivraison(): Collection
    {
        return $this->livraison;
    }

    public function addLivraison(Livraison $livraison): static
    {
        if (!$this->livraison->contains($livraison)) {
            $this->livraison->add($livraison);
            $livraison->setIdUser($this);
        }

        return $this;
    }

    public function removeLivraison(Livraison $livraison): static
    {
        if ($this->livraison->removeElement($livraison)) {
            // set the owning side to null (unless already changed)
            if ($livraison->getIdUser() === $this) {
                $livraison->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cosplay>
     */
    public function getCosplay(): Collection
    {
        return $this->cosplay;
    }

    public function addCosplay(Cosplay $cosplay): static
    {
        if (!$this->cosplay->contains($cosplay)) {
            $this->cosplay->add($cosplay);
            $cosplay->setUserid($this);
        }

        return $this;
    }

    public function removeCosplay(Cosplay $cosplay): static
    {
        if ($this->cosplay->removeElement($cosplay)) {
            // set the owning side to null (unless already changed)
            if ($cosplay->getUserid() === $this) {
                $cosplay->setUserid(null);
            }
        }

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getRoles(): ?string
    {
        return $this->roles;
    }

    public function setRoles(string $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getCin(): ?int
    {
        return $this->cin;
    }

    public function setCin(int $cin): static
    {
        $this->cin = $cin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }

    public function setNumTel(int $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getIsVerified(): ?int
    {
        return $this->is_verified;
    }

    public function setIsVerified(int $is_verified): static
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    /**
     * @return Collection<int, Debat>
     */
    public function getDebat(): Collection
    {
        return $this->debat;
    }

    public function addDebat(Debat $debat): static
    {
        if (!$this->debat->contains($debat)) {
            $this->debat->add($debat);
            $debat->setUserId($this);
        }

        return $this;
    }

    public function removeDebat(Debat $debat): static
    {
        if ($this->debat->removeElement($debat)) {
            // set the owning side to null (unless already changed)
            if ($debat->getUserId() === $this) {
                $debat->setUserId(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservation(): Collection
    {
        return $this->Reservation;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->Reservation->contains($reservation)) {
            $this->Reservation->add($reservation);
            $reservation->setUser($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->Reservation->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UtilisateursType.php
<?php

namespace App\Form;

use App\Entity\Utilisateurs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Type;

class UtilisateursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pseudo', TextType::class)
            ->add('nom', TextType::class, [
                'constraints' => [
                    new NotBlank(),
                    new Regex([
                        'pattern' => '/^[^\d]+$/',
                        'message' => 'Le nom ne doit pas contenir de chiffres.',
                    ]),
                ],
            ])
            ->add('prenom', TextType::class, [
                'constraints' => [
                    new NotBlank(),
                    new Regex([
                        'pattern' => '/^[^\d]+$/',
                        'message' => 'Le prénom ne doit pas contenir de chiffres.',
                    ]),
                ],
            ])
            ->add('age', TextType::class, [
                'constraints' => [
                    new NotBlank(),
                    new GreaterThan([
                        'value' => 18,
                        'message' => 'L\'âge doit être supérieur à 18 ans.',
                    ]),
                    new Type([
                        'type' => 'numeric',
                        'message' => 'L\'âge doit être un nombre.',
                    ]),
                ],
            ])
            ->add('numTel', TextType::class, [
                'constraints' => [
                    new NotBlank(),
                    new Regex([
                        'pattern' => '/^\d{8}$/',
                        'message' => 'Le numéro de téléphone doit contenir exactement 8 chiffres.',
                    ]),
                ],
            ])
            ->add('cin', TextType::class, [
                'constraints' => [
                    new NotBlank(),
                    new Length([
                        'min' => 8,
                        'max' => 8,
                        'exactMessage' => 'Le CIN doit contenir exactement 8 caractères.',
                    ]),
                    new Regex([
                        'pattern' => '/^\d{8}$/',
                        'message' => 'Le CIN doit contenir exactement 8 chiffres.',
                    ]),
                ],
            ])
            ->add('email', TextType::class, [
                'constraints' => [
                    new NotBlank(),
                    new Email([
                        'message' => 'L\'adresse e-mail doit être au bon format.',
                    ]),
                ],
            ])
            ->add('password', PasswordType::class, [
                'mapped' => true,
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        'max' => 4096,
                    ]),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateurs::class,
        ]);
    }
}

templates/utilisateurs/_delete_form.html.twig
<form method="post" action="{{ path('app_utilisateurs_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/utilisateurs/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/utilisateurs/display.html.twig
    {% extends 'home/front.html.twig' %}

    {% block title %}Utilisateurs{% endblock %}
    {% block st %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
        <style type="text/css">
            body{
                margin-top:20px;
                color: #1a202c;
                text-align: left;
                background-color: #e2e8f0;
            }
            .main-body {
                padding: 15px;
            }
            .card {
                box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
            }

            .card {
                position: relative;
                display: flex;
                flex-direction: column;
                min-width: 0;
                word-wrap: break-word;
                background-color: #fff;
                background-clip: border-box;
                border: 0 solid rgba(0,0,0,.125);
                border-radius: .25rem;
            }

            .card-body {
                flex: 1 1 auto;
                min-height: 1px;
                padding: 1rem;
            }

            .gutters-sm {
                margin-right: -8px;
                margin-left: -8px;
            }

            .gutters-sm>.col, .gutters-sm>[class*=col-] {
                padding-right: 8px;
                padding-left: 8px;
            }
            .mb-3, .my-3 {
                margin-bottom: 1rem!important;
            }

            .bg-gray-300 {
                background-color: #e2e8f0;
            }
            .h-100 {
                height: 100%!important;
            }
            .shadow-none {
                box-shadow: none!important;
            }

        </style>
    {% endblock %}

    {% block body %}
        <body>
        <br><br>

        <div class="container">
            <div class="main-body">
                <div class="row gutters-sm">
                    <div class="col-md-4 mb-3">
                        <br><br>
                        <div class="card mt-3">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                    <a href="{{ path('modifier_pass_utilisateur', {'id': app.user.id}) }}">
                                        <button type="submit" class="btn btn-outline-primary btn-block" style="font-size: 16px"> <i class="fa fa-gear"></i> Confidentiality </button>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <br>
                    </div>
                    <div class="col-md-8">
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Pseudo</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ app.user.pseudo}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">First Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ app.user.nom}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Last Name</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{app.user.prenom }}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Email</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ app.user.email }}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Age</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ app.user.age }}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Phone</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        (216){{ app.user.numTel }}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">CIN</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ app.user.cin }}
                                    </div>
                                </div>
                                <hr>
                                <a href="{{ path('modifier_utilisateur', {'id': app.user.id})}}">
                                    <button class="btn btn-primary">Edit Profile</button>
                                </a>
                            </div>
                        </div>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>
        {{ parent() }}
        <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
        <script type="text/javascript">
        </script>
        </body>
    {% endblock %}

templates/utilisateurs/edit.html.twig
{% extends 'home/back.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}
    <br><br><br><br>
    <div class="container align-items-center">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-6">
                <h1>Edit Utilisateurs</h1>

                {{ include('utilisateurs/_form.html.twig', {'button_label': 'Update'}) }}

                <a href="{{ path('app_utilisateurs_index') }}">back to list</a>

                {{ include('utilisateurs/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/utilisateurs/edit1.html.twig
{% extends '../home/back.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}
    <br><br><br><br>
    <div class="container align-items-center">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-6">
                <h1>Edit Utilisateurs</h1>

                {{ include('utilisateurs/_form.html.twig', {'button_label': 'Update'}) }}

                <a href="{{ path('app_utilisateurs_index') }}">back to list</a>

                {{ include('utilisateurs/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/utilisateurs/index.html.twig
{% extends 'home/back.html.twig' %}

{% block title %}Utilisateurs index{% endblock %}


{% block body %}
    <br><br><br><br>
    <style>
        .table {
            width: 100%;
            border-collapse: collapse;
            background-color: #f9f9f9;
        }

        .table th, .table td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: left;
        }

        .table th {
            background-color: #e6e6e6;
        }

        .table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table tr:hover {
            background-color: #ddd;
        }
    </style>
    <div>
        <h1>Utilisateurs index</h1>

        <form method="GET" action="{{ path('app_utilisateurs_index') }}">
            <input type="text" name="q" placeholder="Rechercher par pseudo">
            <button type="submit">Rechercher</button>
        </form>
        <br><br><br>

        <table class="table">
            <thead>
                <tr>
                    <th>Pseudo</th>
                    <th>Roles</th>
                    <th>Cin</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Age</th>
                    <th>NumTel</th>
                    <th>Email</th>
                    <th>IsVerified</th>
                    <th>actions</th>  <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for utilisateur in utilisateurs %}
                <tr>
                    <td>{{ utilisateur.pseudo }}</td>
                    <td>{{ utilisateur.roles ? utilisateur.roles|json_encode : '' }}</td>
                    <td>{{ utilisateur.cin }}</td>
                    <td>{{ utilisateur.nom }}</td>
                    <td>{{ utilisateur.prenom }}</td>
                    <td>{{ utilisateur.age }}</td>
                    <td>{{ utilisateur.numTel }}</td>
                    <td>{{ utilisateur.email }}</td>
                    <td>{{ utilisateur.isVerified ? 'Yes' : 'No' }}</td>
                    <td>
                        <a href="{{ path('app_utilisateurs_show', {'id': utilisateur.id}) }}">show</a>
                    </td>
                     <td>
                            <a href="{{ path('app_indexReservationUtilisateurs_index', {'idUtilisateurs': utilisateur.id}) }}">Liste des Reservations</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="12">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <button><a href="{{ path('app_utilisateurs_new') }}">Create new</a></button>
    </div>
{% endblock %}

templates/utilisateurs/modifierPass.html.twig
{% extends 'home/front.html.twig' %}

{% block title %}Update Password{% endblock %}

{% block body %}

    <br><br><br><br><br><br><br><br><br><br><br>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-6">
                <h1 class="text-center">Update Password</h1>
                {{ form_errors(form) }}

                {{ form_start(form) }}
                {{ form_row(form._token) }}
                <div class="mb-3">
                    {{ form_row(form.plainPassword, {'attr': {'class': 'form-control', 'placeholder': 'Current Password'}}) }}
                    <div class="error-message">{{ form_errors(form.plainPassword) }}</div>
                </div>
                <div class="mb-3">
                    {{ form_row(form.newPassword.first, {'attr': {'class': 'form-control', 'placeholder': 'New Password'}}) }}
                    <div class="error-message">{{ form_errors(form.newPassword.first) }}</div>
                </div>
                <div class="mb-3">
                    {{ form_row(form.newPassword.second, {'attr': {'class': 'form-control', 'placeholder': 'Confirm New Password'}}) }}
                    <div class="error-message">{{ form_errors(form.newPassword.second) }}</div>
                </div>
                <br>
                <button type="submit" class="btn btn-lg btn-primary btn-block">Update Password</button>
            </div>
        </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br>
                

    
{% endblock %}

templates/utilisateurs/new.html.twig
{% extends '/home/back.html.twig' %}

{% block title %}New Utilisateurs{% endblock %}

{% block body %}
    <br><br><br><br>
    <div class="main-content">
        <h1>Create new Utilisateurs</h1>

        {{ include('utilisateurs/_form.html.twig') }}

        <a href="{{ path('app_utilisateurs_index') }}">back to list</a>
    </div>
{% endblock %}

templates/utilisateurs/show.html.twig
{% extends 'home/back.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}
    <br><br><br><br>
    <h1>Utilisateurs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ utilisateur.id }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ utilisateur.pseudo }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ utilisateur.roles ? utilisateur.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Cin</th>
                <td>{{ utilisateur.cin }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ utilisateur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ utilisateur.prenom }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ utilisateur.age }}</td>
            </tr>
            <tr>
                <th>NumTel</th>
                <td>{{ utilisateur.numTel }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ utilisateur.email }}</td>
            </tr>
            <tr>
                <th>IsVerified</th>
                <td>{{ utilisateur.isVerified ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>
    <br><br><br><br>

    <a href="{{ path('app_utilisateurs_index') }}">Back to list</a>


    {{ include('utilisateurs/_delete_form.html.twig') }}
{% endblock %}